/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.aMain;

import src.Dao.BankDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class changepassFrame extends javax.swing.JFrame {

    /**
     * Creates new form changepassFrame
     */
     BankDao dao = new BankDao();
     
    public changepassFrame() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_id = new javax.swing.JLabel();
        TF_id = new javax.swing.JTextField();
        label_pass1_new = new javax.swing.JLabel();
        TF_pass_new1 = new javax.swing.JTextField();
        label_pass_past = new javax.swing.JLabel();
        TF_pass_past = new javax.swing.JTextField();
        label_pass2_new = new javax.swing.JLabel();
        TF_pass_new2 = new javax.swing.JTextField();
        btn_yes = new javax.swing.JButton();
        btn_no = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        label_id.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        label_id.setText("id:");

        TF_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_idActionPerformed(evt);
            }
        });

        label_pass1_new.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        label_pass1_new.setText("新密码：");

        TF_pass_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_pass_new1ActionPerformed(evt);
            }
        });

        label_pass_past.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        label_pass_past.setText("旧密码：");

        label_pass2_new.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        label_pass2_new.setText("确认新密码：");

        btn_yes.setFont(new java.awt.Font("华文彩云", 0, 24)); // NOI18N
        btn_yes.setText("确认");
        btn_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yesActionPerformed(evt);
            }
        });

        btn_no.setFont(new java.awt.Font("华文彩云", 0, 24)); // NOI18N
        btn_no.setText("取消");
        btn_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_noActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("华文琥珀", 0, 24)); // NOI18N
        jLabel1.setText("修改密码");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btn_yes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btn_no)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_pass1_new)
                                    .addComponent(label_pass2_new))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_pass_new2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(TF_pass_new1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_pass_past)
                                    .addComponent(label_id))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_pass_past, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(TF_id)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(TF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_pass_past)
                            .addComponent(TF_pass_past, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_pass1_new)
                            .addComponent(TF_pass_new1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_pass2_new)
                            .addComponent(TF_pass_new2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_yes)
                            .addComponent(btn_no))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_pass_new1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_pass_new1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_pass_new1ActionPerformed

    private void btn_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_noActionPerformed
        this.setVisible(false);
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_btn_noActionPerformed

    private void btn_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yesActionPerformed
       String id_s = TF_id.getText();
       String pass_past = TF_pass_past.getText();
       String pass_new1 = TF_pass_new1.getText();
       String pass_new2 = TF_pass_new2.getText();
       int flag_pass = 1;
       if(pass_new1.length() != 6){
           flag_pass = 0;
       }
       else {
           for(int i = 0; i < pass_new1.length(); i++){
               if(pass_new1.charAt(i) < '0' || pass_new1.charAt(i) > '9')
               {
                   flag_pass = 0;
                   break;
               }
           }
       }
        int flag_id = 1;
        for(int i = 0; i < id_s.length(); i++)
        {
           if(id_s.charAt(i) < '0' || id_s.charAt(i) > '9')
           {
               flag_id = 0;
               break;
           }
        }
        if(id_s.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "请输入您的ID");
        }
        else if(flag_id == 0)
        {
            JOptionPane.showMessageDialog(null, "您输入的ID格式有误");
        }
        else if(pass_past.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "请输入您的旧密码");
        }
        else if(pass_new1.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "请输入您的新密码");
        }
        else if(flag_pass == 0)
        {
            JOptionPane.showMessageDialog(null, "密码必须是6位数字哦");
        }
        else if(pass_new1.equals(pass_past))
        {
            JOptionPane.showMessageDialog(null, "抱歉，新密码不能与旧密码相同");
        }
        else if(pass_new2.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "请确您的新密码");
        }
        else if(!pass_new1.equals(pass_new2))
        {
            JOptionPane.showMessageDialog(null, "两次输入新密码不一致!");
        }
        
        else{
                int id = Integer.parseInt(id_s);
           try {
               if(dao.accountExist(id, pass_past)==1){
                   int result = 0;
                   try {
                       result = dao.changePass(id, pass_past, pass_new1, pass_new2);
                       
                   } catch (ClassNotFoundException ex) {
                       Logger.getLogger(changepassFrame.class.getName()).log(Level.SEVERE, null, ex);
                   } catch (SQLException ex) {
                       Logger.getLogger(changepassFrame.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   if(result == 1){
                       JOptionPane.showMessageDialog(null, "修改密码成功！");
                       this.setVisible(false);
                       new MainFrame().setVisible(true);
                   }
               }
               else{
                   JOptionPane.showMessageDialog(null, "id或密码不正确");
               }
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(changepassFrame.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(changepassFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
                
        }
       
        
    }//GEN-LAST:event_btn_yesActionPerformed

    private void TF_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_id;
    private javax.swing.JTextField TF_pass_new1;
    private javax.swing.JTextField TF_pass_new2;
    private javax.swing.JTextField TF_pass_past;
    private javax.swing.JButton btn_no;
    private javax.swing.JButton btn_yes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_pass1_new;
    private javax.swing.JLabel label_pass2_new;
    private javax.swing.JLabel label_pass_past;
    // End of variables declaration//GEN-END:variables
}
